# Generated by Django 4.2.3 on 2023-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('online_status', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('user_avatar', models.CharField(max_length=100)),
                ('visitor_status', models.BooleanField(default=False)),
                ('collaborator', models.BooleanField(default=False)),
            ],
        ),
    ]
