# Generated by Django 4.2.3 on 2023-07-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(upload_to='uploads/user_avatars'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_creation_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('tags', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('last_edit', models.DateField(auto_now=True)),
                ('upload_status', models.BooleanField(default=False)),
                ('article_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_site.user')),
            ],
        ),
    ]
