# Generated by Django 4.2.3 on 2023-07-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_alter_user_user_avatar_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='collaborator',
            new_name='collaborator_status',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_creation_date', models.DateField(auto_now_add=True, verbose_name='creation_date')),
                ('content', models.TextField()),
                ('last_edit', models.DateField(auto_now=True)),
                ('upload_status', models.BooleanField(default=False)),
                ('comment_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_site.user')),
            ],
        ),
    ]
