# Generated by Django 4.2.3 on 2023-07-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_rename_collaborator_user_collaborator_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lmage',
            field=models.ImageField(default=1, upload_to='uploads/assets'),
            preserve_default=False,
        ),
    ]
