# Generated by Django 4.2.3 on 2023-07-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0005_article_lmage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lmage',
            field=models.ImageField(upload_to='uploads/assets/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(upload_to='uploads/user_avatars/'),
        ),
    ]
