# Generated by Django 4.2.3 on 2023-07-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_alter_article_lmage_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lmage',
            field=models.ImageField(upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(upload_to='user_avatars/'),
        ),
    ]
