# Generated by Django 4.2.3 on 2023-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0007_alter_article_lmage_alter_user_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='lmage',
            new_name='image',
        ),
    ]
